# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hibiscus < Formula
  desc "Modern terminal UI to interact with AWS resources"
  homepage "https://jaehong21.com"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.3.1/hibiscus_Darwin_amd64.tar.gz"
      sha256 "52c7244604a4817fb5db6f221b08a176045d3bfd805c764dd185be0d7aedcee9"

      def install
        bin.install "hibiscus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.3.1/hibiscus_Darwin_arm64.tar.gz"
      sha256 "400f2203988375b5daba68f0659bc900e0c4d11e6e89a3a29018e86a46e62000"

      def install
        bin.install "hibiscus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.3.1/hibiscus_Linux_amd64.tar.gz"
      sha256 "07d7652617c2ad9fcf5e62c1d5fe60db085ae71c24c2c4e1525ab3a7d8063055"
      def install
        bin.install "hibiscus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.3.1/hibiscus_Linux_arm64.tar.gz"
      sha256 "61a074fd7e1596fe8c255a0e96588ee4b09cbd3553e1431f1b83a71eab26fda1"
      def install
        bin.install "hibiscus"
      end
    end
  end

  test do
    system "hibiscus version"
  end
end
