# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hibiscus < Formula
  desc "Modern terminal UI to interact with AWS resources"
  homepage "https://jaehong21.com"
  version "0.2.0-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.2.0-rc.1/hibiscus_Darwin_amd64.tar.gz"
      sha256 "35a8a84975039fac67e2578551cfa4bbf7c5d6c096c9a9daba10eed0b92f4f41"

      def install
        bin.install "hibiscus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.2.0-rc.1/hibiscus_Darwin_arm64.tar.gz"
      sha256 "bd7235009adc88dedb1e1bb358e24f6d53ec175acc841258c91c9ee504c618bf"

      def install
        bin.install "hibiscus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaehong21/hibiscus/releases/download/v0.2.0-rc.1/hibiscus_Linux_amd64.tar.gz"
        sha256 "707e332bb2a9d0688b1c3b4e3fcd77eeb8b3441d39ca1a3ad70153ecc8b0dafb"

        def install
          bin.install "hibiscus"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaehong21/hibiscus/releases/download/v0.2.0-rc.1/hibiscus_Linux_arm64.tar.gz"
        sha256 "eb5cc60d8a964294ee38e7e2dd9f53839a3fb13b70852c1f79cb0510784b6f5d"

        def install
          bin.install "hibiscus"
        end
      end
    end
  end

  test do
    system "hibiscus version"
  end
end
