# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hibiscus < Formula
  desc "Modern terminal UI to interact with AWS resources"
  homepage "https://jaehong21.com"
  version "0.1.0-rc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.1.0-rc/hibiscus_Darwin_amd64.tar.gz"
      sha256 "9eb7fa70b6b2d9c682a90ed54b87f7bcc638174495c561f81ef03763acc63cac"

      def install
        bin.install "hibiscus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.1.0-rc/hibiscus_Darwin_arm64.tar.gz"
      sha256 "78705592bd6b4988cf3d17058da9719dc9958e7bf099a0c8dc95153c7600a170"

      def install
        bin.install "hibiscus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.1.0-rc/hibiscus_Linux_amd64.tar.gz"
      sha256 "c7e1ed205abbf865dea36a224c85e80303667cea7420dd6f48baa0315cdcffcc"

      def install
        bin.install "hibiscus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaehong21/hibiscus/releases/download/v0.1.0-rc/hibiscus_Linux_arm64.tar.gz"
      sha256 "7c926c5d0633c0edfbddbc8c68d172d327350fbda742fa6c7ed863ffd5af09c3"

      def install
        bin.install "hibiscus"
      end
    end
  end

  test do
    system "hibiscus version"
  end
end
